# Example
# https://github.com/netlify/netlify-cms/blob/master/dev-test/config.yml
backend:
    name: test-repo

media_folder: media_folder

collections:
  - name: post
    label: Post
    folder: posts
    create: true
    fields:
    - {name: title, label: Title}
    - {name: body, label: Body, widget: markdown}